name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Validate environment variables
        env:
          VITE_PHONE_NUMBER: ${{ secrets.VITE_PHONE_NUMBER }}
          VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
        run: |
          echo "Checking required environment variables..."

          # Check required VITE_PHONE_NUMBER
          if [ -n "$VITE_PHONE_NUMBER" ]; then
            echo "✅ VITE_PHONE_NUMBER is properly configured"
          else
            echo "⚠️ WARNING: VITE_PHONE_NUMBER environment variable is not set!"
            echo "Configure VITE_PHONE_NUMBER for WhatsApp messaging functionality."
          fi

          # Check required Google Cloud API key
          if [ -n "$VITE_GOOGLE_API_KEY" ]; then
            echo "✅ VITE_GOOGLE_API_KEY is configured (Google Cloud weather integration)"
          else
            echo "⚠️  WARNING: VITE_GOOGLE_API_KEY not configured. Weather section will show error message."
            echo "Configure VITE_GOOGLE_API_KEY for weather functionality."
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build with Vite
        run: pnpm run build
        env:
          ACTIONS_STEP_DEBUG: true
          NODE_ENV: production
          VITE_PHONE_NUMBER: ${{ secrets.VITE_PHONE_NUMBER }}
          VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
